plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'jp.ac.meijou.android.s251205189'
    compileSdk {
        version = release(37)
    }

    defaultConfig {
        applicationId "jp.ac.meijou.android.s251205189"
        minSdk 24
        targetSdk 37
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            optimization {
                enable false
            }
        }
    }
    compileOptions {
        coreLibraryDesugaringEnabled = true
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
    viewBinding {
        enabled = true
    }

}

dependencies {
    coreLibraryDesugaring libs.desuger.jdk.libs
    implementation libs.activity.ktx
    implementation libs.appcompat
    implementation libs.constraintlayout
    implementation libs.material
    testImplementation libs.junit
    androidTestImplementation libs.espresso.core
    androidTestImplementation libs.ext.junit

    implementation libs.datastore.preferences
    implementation libs.datastore.preferences.rxjava3
}